---
- name: debian | Installing Pre-Reqs
  apt:
    name: "{{ item }}"
    state: present
  become: true
  loop:
  - apt-transport-https
  - python-pip

- name: debian | Adding MongoDB Repo Key
  apt_key:
    keyserver: "{{ mongodb_apt_keyserver }}"
    id: "{{ mongodb_apt_gpg_key }}"
    state: present
  become: true

- name: debian | Adding MongoDB Apt Repo
  apt_repository:
    repo: "{{ mongodb_apt_repo_debian }}"
    state: present
  become: true
  when: ansible_distribution == "Debian"

- name: debian | Adding MongoDB Apt Repo
  apt_repository:
    repo: "{{ mongodb_apt_repo_ubuntu }}"
    state: present
  become: true
  when: ansible_distribution == "Ubuntu"

- name: debian | Installing MongoDB
  apt:
    name: "{{ item }}"
    state: present
  become: true
  loop:
  - mongodb-org
  - mongodb-org-server

- name: debian | Enabling and Starting MongoDB Service
  service:
    name: mongod
    state: started
    enabled: true
  become: true
